version: '3'

networks:
  wings-dev-network:
    external: true

services:
  wing-site:
    image: wings-site
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run dev
    networks:
      - wings-dev-network
